on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: access984068551.webspace-data.io
        username: u114315198
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./docs/
        server-dir: ./
